#!/bin/bash

# Bash
ln -snf git/dots/bash/bashrc ~/.bashrc

# Python
ln -snf git/dots/python/pythonrc ~/.pythonrc.py

# Git
ln -snf git/dots/git/gitconfig ~/.gitconfig
ln -snf git/dots/git/gitignore ~/.gitignore
test -f ~/.github || cp ~/git/dots/git/github ~/.github

# Vim
mkdir -p ~/.vim/syntax
ln -snf git/dots/vim/vimrc ~/.vimrc
ln -snf ../../git/dots/vim/text.vim ~/.vim/syntax

# Workspaces
dconf write /org/compiz/profiles/unity/plugins/core/hsize 1
dconf write /org/compiz/profiles/unity/plugins/core/vsize 7

# Shortcuts
KEY="org.gnome.desktop.wm.keybindings"
gsettings set $KEY switch-to-workspace-1 "['<Alt><Shift>i']"
gsettings set $KEY switch-to-workspace-2 "['<Alt><Shift>u']"
gsettings set $KEY switch-to-workspace-3 "['<Alt><Shift>l']"
gsettings set $KEY switch-to-workspace-4 "['<Alt><Shift>k']"
gsettings set $KEY switch-to-workspace-5 "['<Alt><Shift>j']"
gsettings set $KEY switch-to-workspace-6 "['<Alt><Shift>n']"
gsettings set $KEY switch-to-workspace-7 "['<Alt><Shift>m']"
