#!/bin/bash

# Bash
ln -snf git/dots/bash/bashrc ~/.bashrc

# Python
ln -snf git/dots/python/pythonrc ~/.pythonrc.py

# Git
ln -snf git/dots/git/gitconfig ~/.gitconfig
ln -snf git/dots/git/gitignore ~/.gitignore
test -f ~/.github || cp ~/git/dots/git/github ~/.github

# Vim
mkdir -p ~/.vim/syntax
ln -snf git/dots/vim/vimrc ~/.vimrc
ln -snf ../../git/dots/vim/text.vim ~/.vim/syntax
