
# Global
[ -f /etc/bashrc ] && source /etc/bashrc

# History
HISTSIZE=10000
HISTFILESIZE=1000000
HISTCONTROL=ignoreboth
shopt -s histappend

# Aliases
alias l='ls --color -lhgo $*'
alias d='ls --color -lhgod $*'
alias L='ls --color -lhgoa $*'
alias D='ls --color -lhgoda $*'
alias u='du -sk * .[!.]* 2>/dev/null | sort -n'
alias g='glances --theme-white'

# Editor
export EDITOR=vim
set -o vi

# Git
files="/usr/lib/git-core/git-sh-prompt
    /usr/share/git-core/contrib/completion/git-prompt.sh"
for file in $files; do
    test -f $file && source $file
done
export GIT_PS1_SHOWDIRTYSTATE=true

# Prompt
PS1='\u@\h:\w$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (%s)")> '

# Umask
umask 002

# Python
export PYTHONSTARTUP=~/.pythonrc.py
export PYTHONIOENCODING=utf-8:surrogateescape
export PYTHONDONTWRITEBYTECODE=1

# GitHub
source $HOME/.github

# Functions
source ~/git/dot/bash/functions
